function test_std_editset;

eeglab;
tmpp = fileparts(which('checkouteeglab.m'));
[STUDY ALLEEG] = std_editset( [], [], 'commands', ...
    {{'index' 1 'load' fullfile(tmpp, 'unittesting_studyfunc', 'teststudy2','S02', 'Ignore.set') } ...
     {'index' 2 'load' fullfile(tmpp, 'unittesting_studyfunc', 'teststudy2','S02', 'Probe.set' ) } ...
     {'index' 1 'subject' 'S01'} {'index' 2 'subject' 'S01'} {'index' 1 'condition' 'ignore'} ...
     {'index' 2 'condition' 'probe'}},'updatedat','off' );
STUDY = std_makedesign(STUDY, ALLEEG, 1, 'variable1','condition','variable2','load','name','STUDY.design 1','values1',{'ignore' 'probe'},'values2',{3 5 7},'subjselect',{'S01'});
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'commands',{{'remove' 2}},'updatedat','off' );
close
